config/routes.rb
Rails.application.routes.draw do

  resources :users

  root "welcome#index"

  resources :attendees, only: [:destroy]
  resources :comments, only: [:destroy]
  resources :events do
    member do
      post :finished
    end
    resource :venue
    resources :attendees, except: [:destroy]
  end

  resources :venues do 
    resources :tags, :ratings
    resources :comments, except: [:destroy]
    member do
      get 'tag'
    end
  end
  get '/login' => "session#login"
  get '/logout' => "session#logout"
  get '/session/index' => 'session#index'
  post '/check_login' => "session#check_login"

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  def create
    @attendee = Attendee.new(attendee_params)
    @attendee.event_id = params[:event_id]
    @attendee.save
  end
  
  def destroy
    if Attendee.delete(params[:id])
      respond_to do |format|
        format.js do
          render :update do |page|
            page.visual_effect :fade, "attendee_#{params[:id]}"
          end      
        end
      end
    end
  end
  private
  def attendee_params
    params.require(:attendee).permit!
  end

end

app/views/attendees/_attendee.html.erb
<div class="attendee" id="attendee_<%= attendee.id %>">
	<dl>
		<dt>
			<span><%= attendee.name %></span>
			<span style="color: #cccccc; margin: 0 8px 0 8px;">|</span>
			<span style="color: #999999"><%= attendee.email %></span>
		</dt>
		<dd><%= link_to "uninvite", attendee_path(attendee), :method => :delete, remote: true %></dd>
	</dl>
</div>

app/views/attendees/_new.html.erb
<%= form_for Attendee.new, 
	  :url => {:controller => 'attendees', :action => 'create', :event_id => params[:id]}, 
	  :method => :post, remote: true do |f| %>
		
	<label style="font-weight:bold">Name:</label>
	<%= f.text_field :name, :size => 15 %>
	<label style="font-weight:bold">Email:</label>	
	<%= f.text_field :email %>	
	
	<%= submit_tag 'save' %>
<% end %>

app/views/attendees/create.js.erb
$("#attendees").append("<%= j render partial: 'attendee', locals: {attendee: @attendee}%>");
$("#attendee_name").val("");
$("#attendee_email").val("");

app/views/attendees/show.html.erb
<h1>Attendees#show</h1>
<p>Find me in app/views/attendees/show.html.erb</p>