config/routes.rb
Rails.application.routes.draw do

  resources :users

  root "welcome#index"

  resources :attendees, only: [:destroy]
  resources :comments, only: [:destroy]
  resources :events do
    member do
      post :finished
    end
    resource :venue
    resources :attendees, except: [:destroy]
  end

  resources :venues do 
    resources :tags, :ratings
    resources :comments, except: [:destroy]
    member do
      get 'tag'
    end
  end
  get '/login' => "session#login"
  get '/logout' => "session#logout"
  get '/session/index' => 'session#index'
  post '/check_login' => "session#check_login"

end

app/controllers/welcome_controller.rb
 class WelcomeController < ApplicationController

  skip_before_filter :check_authentication, :only => [:index]

  def index
    # @comments = Comment.find(:all, :limit => 5, :order => 'created_at desc')
    @comments = Comment.order(created_at: :desc).limit(5)
    @tags = Tag.limit(25)
  end
  
end

app/views/welcome/index.html.erb
<h3>Have Lunch with Lunched In</h3>

<% if flash[:notice] %>
<span style="color:red;padding-bottom:12px;"><%= flash[:notice] -%></span>
<% end %>

<div id="recent-comments">
	<%= render :partial => 'comments/comment', :collection => @comments %>
</div>

<div class="welcome-links">
	<%= link_to('Find somewhere to eat', venues_path) %>
	<br/><br/>
	<%= link_to('Know somewhere great to eat?', new_venue_path) %>	
</div>

<div class="welcome-tags">
	<% for tag in @tags do %>
		<%= link_to(tag.name, :controller => 'venues', :action => 'tag', :id => tag) %>
	<% end %>
</div>