config/routes.rb
Rails.application.routes.draw do

  resources :users

  root "welcome#index"

  resources :attendees, only: [:destroy]
  resources :comments, only: [:destroy]
  resources :events do
    member do
      post :finished
    end
    resource :venue
    resources :attendees, except: [:destroy]
  end

  resources :venues do 
    resources :tags, :ratings
    resources :comments, except: [:destroy]
    member do
      get 'tag'
    end
  end
  get '/login' => "session#login"
  get '/logout' => "session#logout"
  get '/session/index' => 'session#index'
  post '/check_login' => "session#check_login"

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_many :comments, :as => :commentable
  has_many :ratings

  
  validates_presence_of :name, :address_one, :city, :state, :zip_code
  validates_length_of :zip_code, :is => 5
  
  def tag(name)
    Tag.find_or_create_by(name: name).on(self) unless name.empty?
  end
  
  def rating
    Rating.average(:score, :conditions => ["venue_id = ?", id])
  end
  
  def positive_ratings
    Rating.count(:conditions => ["venue_id = ? and score > 0", id])
  end
    
  def has_user_rated?(user_id)
    ratings.each do |r|
      return true if user_id == r.user_id
    end
    return false
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def index
    @venues = Venue.all
  end

  def new
    @venue = Venue.new
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render :action => 'new'
    end
  end
  
  def tag
    @venues = Tag.find(params[:id]).venues
    render :action => 'index'
  end

  def venue_params
    params.require(:venue).permit!
  end
end

app/views/venues/_venue.html.erb
<div id="venue-<%= venue.id %>" class="venue-item">
	<h3><%= link_to(venue.name, :action => 'show', :id => venue.id) %></h3>
	<div class="venue-address">
		<%= venue.address_one %> <%= venue.city %>, <%= venue.state %> <%= venue.zip_code %>
	</div>
</div>

app/views/venues/create.html.erb
<h1>Venues#create</h1>
<p>Find me in app/views/venues/create.html.erb</p>

app/views/venues/index.html.erb
<%= render(:partial => 'venue', :collection => @venues) unless @venues.blank? %>
<div style="margin-top:14px; padding-left: 10px;	">
	<dl>
		<dd><%= link_to('Add Somewhere to Eat', :action => 'new') %></dd>
	</dl>
</div>

app/views/venues/new.html.erb
<h3>Add A Lunch Restaurant</h3>

<%= error_messages_for @venue %>

<%= form_for @venue, :url => venues_path, :method => :post do |f| %>
<div class="highlighted-form">
	<table>
		<tr>
			<td>Name:</td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td>Address:</td>
			<td><%= f.text_field :address_one %></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><%= f.text_field :address_two %></td>
		</tr>
		<tr>
			<td>City:</td>
			<td><%= f.text_field :city %></td>
		</tr>
		<tr>
			<td>State and Zip:</td>
			<td>
				<%= f.text_field :state, :size => 3 %>
				<%= f.text_field :zip_code, :size => 6 %>
			</td>
		</tr>		
	</table>
  <div style="text-align: right">
	 <%= submit_tag 'Create' %>
  </div>	
</div>



<% end %>

app/views/venues/show.html.erb
	
	<h3><%= @venue.name %></h3>
	<%= render 'tags/cloud' %>

	<div class="highlighted-form">
		<!-- START:has_user_rated -->
    <div id="venue-rating">
   	  <% unless @venue.has_user_rated?(session[:user_id]) %>
   	    <%= render :partial => 'ratings/new' %>
   	  <% else %>
   	    <%= render :partial => 'ratings/show' %>
   	  <% end %>
    </div>
		<!-- END:has_user_rated -->
		<table>
			<tr>
				<td class="label">Address:</td>
				<td><%= @venue.address_one %></td>
			</tr>
			<tr>
				<td class="label">&nbsp;</td>
				<td><%= @venue.address_two %></td>
			</tr>
			<tr>
				<td class="label">Zip Code:</td>
				<td><%= @venue.zip_code %></td>
			</tr>			
			<tr>
				<td class="label">Phone:</td>
				<td><%= @venue.phone_number %></td>
			</tr>
			<tr>
				<td class="label">Fax:</td>
				<td><%= @venue.fax_number %></td>
			</tr>
		</table>
		<div class="venue-update">
			<%= link_to('schedule lunch here', new_event_path(:venue_id => @venue)) %>
		</div>
	</div>
	
	<h4>What is everyone saying?</h4>
	
	<div id="comments">
		<%= render :partial => 'comments/comment', :collection => @venue.comments %>		
	</div>
	
	<%= render :partial => 'comments/new', :locals => { :commentable => @venue }%>
	