config/routes.rb
Rails.application.routes.draw do

  resources :users

  root "welcome#index"

  resources :attendees, only: [:destroy]
  resources :comments, only: [:destroy]
  resources :events do
    member do
      post :finished
    end
    resource :venue
    resources :attendees, except: [:destroy]
  end

  resources :venues do 
    resources :tags, :ratings
    resources :comments, except: [:destroy]
    member do
      get 'tag'
    end
  end
  get '/login' => "session#login"
  get '/logout' => "session#logout"
  get '/session/index' => 'session#index'
  post '/check_login' => "session#check_login"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunched In:  because Lunch is the most important meeting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="content">
 <div id="session-bar">		
	<% if session[:user_id] %>
		<%= link_to 'sign out', '/logout' %>
	<% else %>
		<%= link_to 'login', '/login' %>
	<% end %>
	</div>	
	<div id="header">
		<%= link_to(image_tag("logo.png"), root_path) %>
	</div>
	
	<% unless @hide_tabs %>
  <div id="toolbar">
		<ul id="tablist">
			<li><%= link_to 'Have Lunch', venues_path %></li>
			<% if session[:user_id] %>
			<li><%= link_to 'My Profile', user_path(session[:user_id]) %></li>
			<% else %>
      <li><%= link_to 'Sign Up!', new_user_path %></li>			
			<% end %>
		</ul>
		<div class="lower_toolbar">&nbsp;</div>
		<div class="lower_toolbar_gradient">
			&nbsp;
		</div>
	</div>
	<% end %>

	<div id="body">
    <%= yield %>
	</div>
	<div id="footer">
		<ul>
			<li>&copy; 2008</li>
		</ul>
	</div>
</div>

</body>
</html>